WIP: longhorn-driver: kinda done

diff --git a/package/longhorn/rancher-longhorn b/package/longhorn/rancher-longhorn
--- a/package/longhorn/rancher-longhorn
+++ b/package/longhorn/rancher-longhorn
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -x
+set -e
 
 if [ -e "$(dirname $0)/common.sh" ]; then
     source $(dirname $0)/common.sh
@@ -58,9 +58,7 @@ attach()
 detach()
 {
     # ${DEVICE} will be set with the device that should be detached
-    if ! OUT=$($(dirname $0)/longhorn-driver vol detach "${DEVICE}" 2>${error_file}); then
-        print_error "$(<error_file)"
-    fi
+    # TODO looks like there's nothing to do here
     print_success
 }
 
@@ -69,21 +67,27 @@ mountdest()
     # ${MNT_DEST} will be set with the directory where the filesystem should be mounted
     # ${DEVICE} will be the device returned from attach, if any
     # ${OPTS} will be populated with the options from the JSON input
-    if ! OUT=$($(dirname $0)/longhorn-driver vol mountdest '{"opts":'"${1}"'}' "${MNT_DEST}" "${DEVICE}" 2>${error_file}); then
+    if ! OUT=$(mount "${DEVICE}" "${MNT_DEST}" 2>${error_file}); then
         print_error "$(<error_file)"
     fi
-
     print_success
 }
 
 unmount()
 {
     # ${MNT_DEST} will be set with the directory from which the filesystem should be unmounted
-    if ! OUT=$($(dirname $0)/longhorn-driver vol unmount "${MNT_DEST}" 2>${error_file}); then
-        print_error "$(<error_file)"
+    if ! OUT=$(umount "${MNT_DEST}" 2>${error_file}); then
+        local err
+        err=$(<error_file)
+        if [ "$(echo ${err} | grep 'not mounted')" ]; then
+            print_success "not mounted"
+        elif [ "$(echo ${err} | grep 'mountpoint not found')" ]; then
+            print_success "not found"
+        else
+            print_error "${err}"
+        fi
     fi
-
-    print_success
+    print_success "unmounted"
 }
 
 # Every script must call main as such
